spring:
#  profiles:
#    default: local
  data:
    mongodb:
      uri: ${AUTH_SERVICE_MONGODB_URI}
      auto-index-creation: true
      uuid-representation: standard
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER}
    consumer:
      group-id: auth-service

management:
  info:
    env:
      enabled: true
  endpoints:
    enabled-by-default: true
  endpoint:
    health:
      probes:
        enabled: true



password:
  minCharacterLength: 20
  maxCharacterLength: 25

jwt-config:
  issuer: ${AUTH_SERVICE_URL}
  oidcIssuerDiscoveryEndpoint: ${EXTERNAL_OIDC_PROVIDER_DISCOVERY_ENDPOINT}
  publicKeyBase64: ${JWT_PUBLIC_KEY_BASE64}
  privateKeyBase64: ${JWT_PRIVATE_KEY_BASE64}
  keyId: ${JWT_KEY_ID}
  validityInSeconds: ${JWT_VALIDITY_IN_SECONDS}
  keyAlgorithm: ${JWT_KEY_ALGORITHM}
  signingAlgorithm: ${JWT_SIGNING_ALGORITHM}

server:
  port: 8080
