spring:
#  profiles:
#    default: local
  data:
    mongodb:
      uri: mongodb://localhost:27017/auth-service
      auto-index-creation: true
      uuid-representation: standard

logging:
  level:
    org:
      springframework: debug

jwt-config:
  issuer: http://localhost:8080
  oidcIssuers:
#    - https://idp.example.org/issuerOne
#   - https://idp.example.org/issuerTwo
  publicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAhweBNtTB1Cp78qyBRuhvqVjcT/DwZYKcaakP3aR83OlQ3rwKhvlvH10afx1w0aSOaO/efUYvwAl+R6/4V+RJPLDXcrAwe7dTQ9Ba8dmFx/A9ge9NtPqyvmDbx9eKEIEjOHNYmSBauDnHCxQIkL58BoSipfKEZngXMrEvBL9MGNZ00gl3aLkqbbf/6yWRtpN3BFsUgTTsau/dcJqcSr92aRzJG77683PEX4UqJi2XeEci589+OeS9Xk3hf4UPMHiQjJOogDfaQg9z0ErIIJbumi0as9Pw0/m8BIHykL9LrJc+37Zs74YJbgbVWhrJ4cBhFdmITserae91YwJ9G3LrBwIDAQAB
  privateKey: MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCHB4E21MHUKnvyrIFG6G+pWNxP8PBlgpxpqQ/dpHzc6VDevAqG+W8fXRp/HXDRpI5o7959Ri/ACX5Hr/hX5Ek8sNdysDB7t1ND0Frx2YXH8D2B7020+rK+YNvH14oQgSM4c1iZIFq4OccLFAiQvnwGhKKl8oRmeBcysS8Ev0wY1nTSCXdouSptt//rJZG2k3cEWxSBNOxq791wmpxKv3ZpHMkbvvrzc8RfhSomLZd4RyLnz3455L1eTeF/hQ8weJCMk6iAN9pCD3PQSsgglu6aLRqz0/DT+bwEgfKQv0uslz7ftmzvhgluBtVaGsnhwGEV2YhOx6tp73VjAn0bcusHAgMBAAECggEAAbusbRDnrfqfnaVDgYP75D9iOy/F/h+M32ROnP3T+8fjhFWt3ZP3rlOKbVrqNvP26feOMlXDc3e2ZGLTUVl6QSpUkZcbqt2BrECmh4J5ukUQnQl+b1YPvkF4VgUjs1jc+V1YTprWNJV1Qw9ORCwAY9sG9WdP9hAQ3X3dsyC7cCQnv1bI6YwVmThN10BMkkVzLdxNSCDdEnhV3fACs97ZPRTHZlyeGB9FVI9m/lIk93KcMqtCc88HOAja3b+8pfT5v3Lu7sC/Yd35siLQRMCOMyifqkqOShd+O2eYNSEWWG0kz0arTIUJ+E/ZlUf0AkCcw4/czhjHdi0IulXR+9+dxQKBgQC9XH11p4gK4YF0P+evz+tiM6pdQqZoJQmxNicP8z2oFYQfcGzlTxTMzAkVC+XZIPDHNF9f7x3TDUs/W2sqeTabWYh4I7zfvczUC4bc2VHDtKUDuNX6BYqpnSEdsSaMssi+YgYeo4AOb7j7Kr7JQUBucg/9F1aWdNIAFj6vFhTEJQKBgQC2jELWlvDDCZRqbawBeun8X6JRXNhPA3rXYwQ4BnyMW2cCskOxShLyjiOA30xFl4eQ7RKMPT1ldAmc1YzdDGJbu+P3FrtbHAREIO0voh5HCJWVw3v8mDnqt/q+B9T2T4g6q2WRWKbtpdjQqO6OFQZb/VNzL6fLXy24Cmd+LKXUuwKBgBkbFyMvOBFBPrmb82rS5UFa2j6NJKTwLC3LoTgzJryPRbopXLa2Wmqgrp+UuT+lZ2bx4adFe63MuGpJA5dZBM1p/Hb5PgRoFK0Ubif/xCBvZeVtbyk77Nt6ErbuEs9asNTVCDytrr+7PkpGq47hUNqT0tzaaEeAa4tJZ7ws8EnlAoGADcHWS6vGazxulfK78sSbm6xtZCpWFuZRPKg2qi469qzwv3BFz7egY+04Wb76VYhM7CwhqLX4yYuMKeiiHAqR4w3u6TEqX3xmCehdV6ilFX9dHpND5c5nFvxUhju63fEyeBFwrxp6QhCsnVUN3WFSQF6ACn896wK6RFNsZ0LgIH8CgYA8WXRiwIRm7iy1QkoWlbJYJNXSigrj6yl2n8Fa+WU/oCraI0iQYCwmHnTTICMjSWyMLxGv7FCXIa1MX1cHNdGgLyuMOJ+jafaQU4dVgOVB4OL/5mS2bFQxmpM7Lw0CLEATEtRncYh4ECU81UWvtJO3xmtQYkws2P0Q13cyzAqVkw==
  keyId: 4dbacae9-3b24-46c0-8ecb-332b9bdd25ec
  validityInSeconds: 86400
  keyAlgorithm: RSA
  signingAlgorithm: RS256

server:
  port: 8080
