version: '3.8'
services:

  nginx:
    image: nginx:latest
    container_name: nginx_container
    ports:
      - "80:80"
    volumes:
      - ./templates:/etc/nginx/templates
    networks:
      - my-network
    depends_on:
      auth-service:
        condition: service_healthy
      user-service:
        condition: service_healthy
      career-service:
        condition: service_healthy
      notification-service:
        condition: service_healthy
      frontend:
        condition: service_healthy
    environment:
      - FRONTEND_URL
      - AUTH_SERVICE_URL
      - AUTH_NGINX_ENDPOINT
      - USER_SERVICE_URL
      - USER_NGINX_ENDPOINT
      - CAREER_SERVICE_URL
      - CAREER_NGINX_ENDPOINT

  mongodb:
    image: mongo
    networks:
      - my-network
    expose:
      - "27017"
    volumes:
      - ./volumes/mongo-data:/data/db
      - ./auth-service/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
      - MONGO_INITDB_DATABASE
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 20s

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      - ZOOKEEPER_CLIENT_PORT
      - ZOOKEEPER_TICK_TIME
    networks:
      - my-network
    expose:
      - '2181'
    volumes:
      - ./volumes/zookeeper/data:/var/lib/zookeeper/data
      - ./volumes/zookeeper/log:/var/lib/zookeeper/log
    healthcheck:
      test: nc -z localhost 2181 || exit -1
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 20s

  kafka-event:
    image: confluentinc/cp-kafka:latest
    depends_on:
      zookeeper:
        condition: service_healthy
    networks:
      - my-network
    hostname: kafka-event
    expose:
      - "9092"
    volumes:
      - ./volumes/kafka-broker/data:/var/lib/kafka/data
    environment:
      - KAFKA_ZOOKEEPER_CONNECT
      - KAFKA_ADVERTISED_HOST_NAME
      - KAFKA_ADVERTISED_LISTENERS
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
    healthcheck:
      test: nc -z localhost 9092 || exit -1
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 20s

  eventstoredb:
    image: eventstore/eventstore:23.6.0-buster-slim
    # For ARM-based processors
    # image: eventstore/eventstore:23.6.0-alpha-arm64v8
    environment:
      - EVENTSTORE_CLUSTER_SIZE
      - EVENTSTORE_RUN_PROJECTIONS
      - EVENTSTORE_START_STANDARD_PROJECTIONS
      - EVENTSTORE_EXT_TCP_PORT
      - EVENTSTORE_HTTP_PORT
      - EVENTSTORE_INSECURE
      - EVENTSTORE_ENABLE_EXTERNAL_TCP
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP
    expose:
      - '1113'
      - '2113'
    volumes:
      - ./volumes/eventstore-volume-data:/var/lib/eventstore
      - ./volumes/eventstore-volume-logs:/var/log/eventstore
    networks:
      - my-network


  frontend:
    build: ./frontend/.
    #image: caschuen/cnd-joboffers-frontend
    networks:
      - my-network
    expose:
      - "8080"
    environment:
      - EXTERNAL_AUTH_SERVICE_URL
      - EXTERNAL_USER_SERVICE_URL
      - EXTERNAL_CAREER_SERVICE_URL
      - APP_ENV
      - OIDC_PROVIDER_DISCOVERY_ENDPOINT
      - OIDC_CLIENT_ID
      - OIDC_CLIENT_SECRET
      - OIDC_CLIENT_REDIRECT_URL
    healthcheck:
      test: "curl -sf http://localhost:8080 || exit 1"
      interval: 20s
      timeout: 10s
      retries: 10
      start_period: 40s


  auth-service:
    build: ./authservice/.
    networks:
      - my-network
    expose:
      - "8080"
    depends_on:
      mongodb:
          condition: service_healthy
      kafka-event:
        condition: service_healthy
    environment:
      - AUTH_SERVICE_MONGODB_URI
      - KAFKA_BOOTSTRAP_SERVER
      - USER_SERVICE_URL
      - AUTH_SERVICE_URL
      - OIDC_PROVIDER_DISCOVERY_ENDPOINT
      - JWT_PUBLIC_KEY_BASE64
      - JWT_PRIVATE_KEY_BASE64
      - JWT_KEY_ID
      - JWT_VALIDITY_IN_SECONDS
      - JWT_KEY_ALGORITHM
      - JWT_SIGNING_ALGORITHM

    healthcheck:
      test: "curl --fail --silent localhost:8080/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 20s

  user-service:
    build: ./userservice/.
    networks:
      - my-network
    expose:
      - "8080"
    depends_on:
      mongodb:
        condition: service_healthy
      kafka-event:
        condition: service_healthy
      auth-service:
          condition: service_healthy
    environment:
      - AUTH_SERVICE_URL
      - KAFKA_BOOTSTRAP_SERVER
      - USER_SERVICE_MONGODB_URI
    healthcheck:
      test: "curl --fail --silent localhost:8080/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 20s

  career-service:
    build: ./careerservice/.
    networks:
      - my-network
    expose:
      - "8080"
    depends_on:
      mongodb:
        condition: service_healthy
      kafka-event:
        condition: service_healthy
      eventstoredb:
        condition: service_healthy
      auth-service:
        condition: service_healthy
      user-service:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE
      - KAFKA_BOOTSTRAP_SERVER
      - EVENT_STORE_URI
      - CAREER_SERVICE_MONGODB_URI
      - CAREER_SERVICE_CLIENT_SECRET
      - AUTH_SERVICE_URL
      - USER_SERVICE_URL
    healthcheck:
      test: "curl --fail --silent localhost:8080/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 20s


  notification-service:
    build: ./notificationservice/.
    networks:
      - my-network
    expose:
      - "8080"
    depends_on:
      mongodb:
        condition: service_healthy
      kafka-event:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE
      - KAFKA_BOOTSTRAP_SERVER
    healthcheck:
      test: "curl --fail --silent localhost:8080/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 20s

networks:
  my-network:
    name: my-network
