apiVersion: v1
kind: Secret
metadata:
  name: career-service-secret-config
type: Opaque
data:
  # CAREER SERVICE
  CAREER_SERVICE_CLIENT_SECRET: NmtvKlkoa2tNVD5XLHFXS1U0blU1Uw==
  CAREER_SERVICE_MONGODB_URI:  {{ (tpl "mongodb://root:root@{{ .Values.mongodb.serviceName }}:{{ .Values.mongodb.port }}/{{ .Values.microservices.careerService.dbName }}?authSource=admin&readPreference=primary&directConnection=true&ssl=false" .) | b64enc }}
