apiVersion: v1
kind: ConfigMap
metadata:
  name: career-service-config-map
  namespace: default
data:
  {{- with .Values.microservices.careerService }}
  CAREER_SERVICE_CLIENT_ID: "{{ .oAuth2ClientID }}"
  CAREER_SERVICE_PORT: "{{ .port }}"
  {{- end }}

  KAFKA_BOOTSTRAP_SERVER: "{{ tpl .Values.kafka.bootstrapServer . }}"

  {{- with .Values.microservices.frontend }}
  OIDC_PROVIDER_DISCOVERY_ENDPOINT: "{{ .oidc.discoveryEndpoint }}"
  {{- end }}

  {{- with .Values.microservices.userService }}
  USER_SERVICE_URL: "{{ tpl .url $ }}"
  {{- end }}

  {{- with .Values.microservices.authService }}
  INTERNAL_JWT_ISSUER_URL: "{{ tpl (tpl $.Values.auth.internalJwtIssuerUrl $) $ }}"
  {{- end }}

  EVENT_STORE_URI: "{{ tpl .Values.eventstore.connectionUrl $ }}"
