apiVersion: v1
kind: Service
metadata:
  labels:
    app: eventstoredb
  name: {{ .Values.eventstore.serviceName }}
spec:
  ports:
    - name: eventstoredb-port-1113
      port: {{ .Values.eventstore.dbPort }}
      protocol: TCP
      targetPort: {{ .Values.eventstore.dbPort }}
    - name: eventstoredb-port-2113
      port: {{ .Values.eventstore.webUIPort }}
      protocol: TCP
      targetPort: {{ .Values.eventstore.webUIPort }}
  selector:
    app: eventstoredb

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: eventstoredb
  name: eventstoredb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eventstoredb
  strategy: {}
  template:
    metadata:
      labels:
        app: eventstoredb
    spec:
      containers:
        - image: "{{ .Values.eventstore.image }}:{{ .Values.eventstore.imageTag }}"
          name: eventstoredb
          ports:
            - containerPort: {{ .Values.eventstore.dbPort }}
            - containerPort: {{ .Values.eventstore.webUIPort }}
          envFrom:
            - configMapRef:
                name: job-offers-config-map
          volumeMounts:
            - name: "eventstoredb-data"
              mountPath: "/var/lib/eventstore"
            - name: "eventstoredb-log"
              mountPath: "/var/log/eventstore"
      volumes:
        - name: "eventstoredb-data"
          persistentVolumeClaim:
            claimName: "eventstoredb-data-claim"
        - name: "eventstoredb-log"
          persistentVolumeClaim:
            claimName: "eventstoredb-log-claim"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: eventstoredb-data-claim
  namespace: default
  labels:
    app: eventstoredb
spec:
  accessModes:
    - ReadWriteOnce
  volumeName: eventstoredb-data-volume
  storageClassName: hostpath
  resources:
    requests:
      storage: 500Mi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: eventstoredb-log-claim
  namespace: default
  labels:
    app: eventstoredb
spec:
  accessModes:
    - ReadWriteOnce
  volumeName: eventstoredb-log-volume
  storageClassName: hostpath
  resources:
    requests:
      storage: 500Mi


---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: eventstoredb-data-volume
  labels:
    type: local
spec:
  capacity:
    storage: 500Mi
  claimRef:
    name: eventstoredb-data-claim
    namespace: default
  accessModes:
    - ReadWriteOnce
  hostPath:
    type: DirectoryOrCreate
    path: {{ $.Values.localConfig.mountBasePath }}/eventstore-volume-data

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: eventstoredb-log-volume
  labels:
    type: local
spec:
  capacity:
    storage: 500Mi
  claimRef:
    name: eventstoredb-log-claim
    namespace: default
  accessModes:
    - ReadWriteOnce
  hostPath:
    type: DirectoryOrCreate
    path: {{ $.Values.localConfig.mountBasePath }}/eventstore-volume-logs

