apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka-event
  name: {{ .Values.kafka.serviceName }}
spec:
  ports:
    - port: {{ .Values.kafka.port }}
      protocol: TCP
      targetPort: 9092
  selector:
    app: kafka-event

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kafka-event
  name: kafka-event
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-event
  strategy: {}
  template:
    metadata:
      labels:
        app: kafka-event
    spec:
      containers:
        - image: confluentinc/cp-kafka:{{ .Values.kafka.imageTag }}
          name: kafka-event
          securityContext:
            runAsUser: 0
            runAsGroup: 0
          ports:
            - containerPort: 9092
          envFrom:
            - configMapRef:
                name: kafka-config-map
          volumeMounts:
            - name: "kafka-data"
              mountPath: "/var/lib/kafka/data"
      volumes:
        - name: "kafka-data"
          persistentVolumeClaim:
            claimName: "kafka-data-claim"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka-data-claim
  labels:
    app: kafka-event
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  volumeName: kafka-volume
  storageClassName: standard
  resources:
    requests:
      storage: 500Mi

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-volume
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  claimRef:
    name: kafka-data-claim
    namespace: default
  hostPath:
    type: DirectoryOrCreate
    path: {{ $.Values.localConfig.mountBasePath }}/kafka-broker/data


