apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongodb
  name: {{ .Values.mongodb.serviceName }}
spec:
  ports:
    - port: {{ .Values.mongodb.port }}
      protocol: TCP
      targetPort: 27017
  selector:
    app: mongodb

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mongodb
  name: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  strategy: {}
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
      containers:
        - image: "mongo:{{ .Values.mongodb.imageTag }}"
          name: mongodb
          ports:
            - containerPort: 27017
          envFrom:
            - secretRef:
                name: mongodb-secret-config
          volumeMounts:
            - name: "mongo-mount"
              mountPath: "/data/db"
            - name: "mongo-init-database"
              mountPath: /docker-entrypoint-initdb.d/mongo-init.js
              subPath: mongo-init.js

      volumes:
        - name: "mongo-mount"
          persistentVolumeClaim:
            claimName: "mongodb-volume-claim"
        - name: "mongo-init-database"
          configMap:
            name: init-mongodb-configmap

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-volume
  labels:
    type: local
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: default
    name: mongodb-volume-claim
  storageClassName: standard
  hostPath:
    type: DirectoryOrCreate
    path: {{ $.Values.localConfig.mountBasePath }}/mongo-data

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-volume-claim
  namespace: default
  labels:
    app: mongodb
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  volumeName: mongodb-volume
  resources:
    requests:
      storage: 500Mi

---

apiVersion: v1
data:
  mongo-init.js: {{ tpl .Values.mongodb.startupScript . | toYaml | indent 1 }}
kind: ConfigMap
metadata:
  creationTimestamp: "2023-11-06T20:13:43Z"
  name: init-mongodb-configmap
  namespace: default
  resourceVersion: "66814"
  uid: 8c7f6bbb-a59f-46d9-8a1a-49d2bee9f024
