apiVersion: v1
kind: Secret
metadata:
  name: user-service-secret-config
type: Opaque
data:
  # CAREER SERVICE
  USER_SERVICE_MONGODB_URI: {{ (tpl "mongodb://root:root@{{ .Values.mongodb.serviceName }}:{{ .Values.mongodb.port }}/{{ .Values.microservices.userService.dbName }}?authSource=admin&readPreference=primary&directConnection=true&ssl=false" . ) | b64enc }}
