{{- with .Values.microservices.userService }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .serviceName }}
  labels:
    app: {{ .name }}
spec:
  selector:
    app: {{ .name }}
  ports:
    - port: {{ .port }}
      protocol: TCP
      targetPort: {{ .port }}
  type: ClusterIP

---

apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ .name }}
  labels:
    app: {{ .name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .name }}
  template:
    metadata:
      labels:
        app: {{ .name }}
    spec:
      containers:
        - name: {{ .name }}
          image: "{{ .image }}:{{ .imageTag }}"
          envFrom:
            - configMapRef:
                name: user-service-config-map
            - secretRef:
                name: user-service-secret-config
          ports:
            - containerPort: {{ .port }}
      restartPolicy: Always
{{- end }}
