spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}
      auto-index-creation: true
      uuid-representation: standard
  kafka:
    producer:
      retries: 5
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER}
    consumer:
      group-id: user-service
  security:
    oauth2:
      resource-server:
        jwt:
          jwk-set-uri: "${AUTH_SERVICE_URL}/oauth2/jwks"
          audiences: user-service

management:
  info:
    env:
      enabled: true
  endpoints:
    enabled-by-default: true
  endpoint:
    health:
      probes:
        enabled: true

server:
  port: 8080

event:
  kafka:
    topics:
      user-service_user-registered:
        name: user-service_user-registered
        partitions: 1
        replicas: 1
      user-service_company-registered:
        name: user-service_company-registered
        partitions: 1
        replicas: 1
      user-service_user-invited-to-company:
        name: user-service_user-invited-to-company
        partitions: 1
        replicas: 1
      user-service_company-name-changed:
        name: user-service_company-name-changed
        partitions: 1
        replicas: 1
      user-service_company-deleted:
        name: user-service_company-deleted
        partitions: 1
        replicas: 1
      user-service_user-deleted:
        name: user-service_user-deleted
        partitions: 1
        replicas: 1
