spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/user-service
      auto-index-creation: true
      uuid-representation: standard
  security:
    oauth2:
      resourceserver:
        jwt:
          #issuer-uri: http://localhost:8081
          jwk-set-uri: http://localhost:8081/oauth2/jwks

server:
  port: 8082

security:
  csrfActive: false
  corsActive: false