spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          #issuer-uri: http://localhost:8081
          jwk-set-uri: http://localhost:8081/oauth2/jwks

server:
  port: 8082

security:
  csrfActive: false
  corsActive: false