apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka-event
  name: kafka-event
spec:
  ports:
    - port: 9092
      protocol: TCP
      targetPort: 9092
  selector:
    app: kafka-event

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kafka-event
  name: kafka-event
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-event
  strategy: {}
  template:
    metadata:
      labels:
        app: kafka-event
    spec:
      containers:
        - image: confluentinc/cp-kafka:latest
          name: kafka-event
          ports:
            - containerPort: 9092
          envFrom:
            - configMapRef:
                name: job-offers-config-map
          volumeMounts:
            - name: "kafka-data"
              mountPath: "/var/lib/kafka/data"
      volumes:
        - name: "kafka-data"
          persistentVolumeClaim:
            claimName: "kafka-data-claim"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka-data-claim
  labels:
    app: kafka-event
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: ./volumes/kafka


