apiVersion: v1
kind: Service
metadata:
  labels:
    app: zookeeper
  name: zookeeper
spec:
  ports:
    - port: 2181
      protocol: TCP
      targetPort: 2181
  selector:
    app: zookeeper

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: zookeeper
  name: zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  strategy: {}
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
        - image: confluentinc/cp-zookeeper:latest
          name: zookeeper
          ports:
            - containerPort: 2181
          envFrom:
            - configMapRef:
                name: job-offers-config-map
          volumeMounts:
            - name: "zookeeper-data"
              mountPath: "/var/lib/zookeeper/data"
            - name: "zookeeper-log"
              mountPath: "/var/lib/zookeeper/log"
      volumes:
        - name: "zookeeper-data"
          persistentVolumeClaim:
            claimName: "zookeeper-data-claim"
        - name: "zookeeper-log"
          persistentVolumeClaim:
            claimName: "zookeeper-log-claim"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zookeeper-data-claim
  labels:
    app: zookeeper
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zookeeper-log-claim
  labels:
    app: zookeeper
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: zookeeper-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: ./volumes/zookeeper
