spring:
  data:
    mongodb:
      uri: ${USER_SERVICE_MONGODB_URI:mongodb://localhost:27017/user-service?authSource=admin&readPreference=primary&directConnection=true&ssl=false}
      auto-index-creation: true
      uuid-representation: standard
  kafka:
    producer:
      retries: 5
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER:http://localhost:9092}
    consumer:
      group-id: user-service
  security:
    oauth2:
      resource-server:
        jwt:
          jwk-set-uri: ${INTERNAL_JWT_ISSUER_URL:http://localhost:8081}/oauth2/jwks}
          audiences: user-service

logging:
  level:
    org.springframework.web: DEBUG

management:
  info:
    env:
      enabled: true
  endpoints:
    enabled-by-default: true
  endpoint:
    health:
      probes:
        enabled: true

server:
  port: ${USER_SERVICE_PORT:8082}

event:
  kafka:
    topics:
      user-service_user-registered:
        name: user-service_user-registered
        partitions: 1
        replicas: 1
      user-service_company-registered:
        name: user-service_company-registered
        partitions: 1
        replicas: 1
      user-service_user-invited-to-company:
        name: user-service_user-invited-to-company
        partitions: 1
        replicas: 1
      user-service_company-name-changed:
        name: user-service_company-name-changed
        partitions: 1
        replicas: 1
      user-service_company-deleted:
        name: user-service_company-deleted
        partitions: 1
        replicas: 1
      user-service_user-deleted:
        name: user-service_user-deleted
        partitions: 1
        replicas: 1
