openapi: 3.0.0
info:
  title: User-Service
  description: API.
  version: 0.0.1
paths:
  /users/register:
    post:
      summary: Register a new user.
      operationId: registerNewUser
      tags:
        - User
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRegistrationRequest'
      responses:
        '200':
          description: Registration was successful.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        default:
          description: Returned if any error occurred during the request.
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ThrowableProblem'
  /users/{user-id}:
    get:
      description: Get user of provided user id.
      operationId: getUser
      tags:
        - User
      parameters:
        - $ref: '#/components/parameters/UserId'
      responses:
        '200':
          description: User was found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        default:
          description: Returned if any error occurred during the request.
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ThrowableProblem'
    delete:
      description: Deletes the user.
      operationId: deleteUser
      tags:
        - User
      parameters:
        - $ref: '#/components/parameters/UserId'
      responses:
        '204':
          description: User was deleted.
        default:
          description: Returned if any error occurred during the request.
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ThrowableProblem'
  /users/{user-id}/public-profile:
    get:
      description: Get user public profile of provided user id.
      operationId: getPublicUserProfile
      tags:
        - User
      parameters:
        - $ref: '#/components/parameters/UserId'
      responses:
        '200':
          description: User was found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PublicUserProfile'
        default:
          description: Returned if any error occurred during the request.
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ThrowableProblem'
  /users/{user-id}/update-user-settings:
    put:
      description: Update the user settings associated with this user.
      operationId: updateUserSettings
      tags:
        - User
      parameters:
        - $ref: '#/components/parameters/UserId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateUserSettingsRequest'
      responses:
        '200':
          description: User data was updated.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        default:
          description: Returned if any error occurred during the request.
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ThrowableProblem'
  /users/{user-id}/update-user-profile:
    put:
      description: Update the user profile associated with this user.
      operationId: updateUserProfile
      tags:
        - User
      parameters:
        - $ref: '#/components/parameters/UserId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateUserProfileRequest'
      responses:
        '200':
          description: User data was updated.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        default:
          description: Returned if any error occurred during the request.
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ThrowableProblem'
  /users/{user-id}/subscribe:
    post:
      summary: Makes the user a subscriber or extends their subscription.
      operationId: subscribe
      tags:
        - User
      parameters:
        - $ref: '#/components/parameters/UserId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExtendUserSubscriptionRequest'
      responses:
        '200':
          description: Subscription was successful.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        default:
          description: Returned if any error occurred during the request.
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ThrowableProblem'
  /users/{user-id}/accept-company-invitation:
    post:
      summary: Accepts the invitation to be a member of a company.
      operationId: acceptInvitation
      tags:
        - User
      parameters:
        - $ref: '#/components/parameters/UserId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AcceptCompanyInvitationRequest'
      responses:
        '200':
          description: Invitation was accepted.
        default:
          description: Returned if any error occurred during the request.
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ThrowableProblem'
  /companies/register:
    post:
      summary: Creates a new company.
      operationId: createNewCompany
      tags:
        - Company
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CompanyRegistrationRequest'
      responses:
        '200':
          description: Registration was successful.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Company'
        default:
          description: Returned if any error occurred during the request.
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ThrowableProblem'
  /companies/{company-id}:
    get:
      description: Get company for provided id.
      operationId: getCompany
      tags:
        - Company
      parameters:
        - $ref: '#/components/parameters/CompanyId'
      responses:
        '200':
          description: Company was found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Company'
        default:
          description: Returned if any error occurred during the request.
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ThrowableProblem'
    delete:
      description: Deletes the company.
      operationId: deleteCompany
      tags:
        - Company
      parameters:
        - $ref: '#/components/parameters/CompanyId'
      responses:
        '204':
          description: The company was deleted.
        default:
          description: Returned if any error occurred during the request.
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ThrowableProblem'
  /companies/{company-id}/public-profile:
    get:
      description: Get company for provided id.
      operationId: getPublicCompanyProfile
      tags:
        - Company
      parameters:
        - $ref: '#/components/parameters/CompanyId'
      responses:
        '200':
          description: Company was found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PublicCompanyProfile'
        default:
          description: Returned if any error occurred during the request.
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ThrowableProblem'
  /companies/{company-id}/invite-user:
    post:
      description: Invites an user to join the company.
      operationId: inviteUserToCompany
      tags:
        - Company
      parameters:
        - $ref: '#/components/parameters/CompanyId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CompanyInviteUserRequest'
      responses:
        '200':
          description: Invitation was sent.
        default:
          description: Returned if any error occurred during the request.
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ThrowableProblem'
  /companies/{company-id}/partner-program:
    post:
      description: Subscribes to partner program
      operationId: subscribeToPartnerProgram
      tags:
        - Company
      parameters:
        - $ref: '#/components/parameters/CompanyId'
      responses:
        '200':
          description: Successfully subscribed to partner program.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Company'
        default:
          description: Returned if any error occurred during the request.
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ThrowableProblem'
  /companies/{company-id}/update-company-details:
    put:
      description: Overrides the current company details with the provided data.
      operationId: updateCompanyDetails
      tags:
        - Company
      parameters:
        - $ref: '#/components/parameters/CompanyId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateCompanyDetailsRequest'
      responses:
        '200':
          description: Registration was successful.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Company'
        default:
          description: Returned if any error occurred during the request.
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ThrowableProblem'
  /companies/{company-id}/update-company-links:
    put:
      description: Overrides the current company links with the provided data.
      operationId: updateCompanyLinks
      tags:
        - Company
      parameters:
        - $ref: '#/components/parameters/CompanyId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateCompanyLinksRequest'
      responses:
        '200':
          description: Registration was successful.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Company'
        default:
          description: Returned if any error occurred during the request.
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ThrowableProblem'

components:
  parameters:
    UserId:
      in: path
      name: user-id
      schema:
        $ref: '#/components/schemas/UUID'
      required: true
    CompanyId:
      in: path
      name: company-id
      schema:
        $ref: '#/components/schemas/UUID'
      required: true
    Page:
      in: query
      name: page
      schema:
        type: integer
    Size:
      in: query
      name: size
      schema:
        type: integer
  schemas:
    PublicUserProfile:
      type: object
      required:
        - id
        - first_name
        - last_name
        - user_profile_email
      properties:
        id:
          $ref: '#/components/schemas/UUID'
        first_name:
          type: string
        last_name:
          type: string
        user_profile_email:
          type: string
    User:
      type: object
      required:
        - id
        - profile
        - associations
        - settings
        - subscription
      properties:
        id:
          $ref: '#/components/schemas/UUID'
        profile:
          $ref: '#/components/schemas/UserProfile'
        associations:
          $ref: '#/components/schemas/UserCompanyAssociation'
        settings:
          $ref: '#/components/schemas/UserSettings'
        subscription:
          $ref: '#/components/schemas/UserSubscription'
    UserProfile:
      type: object
      required:
        - user_profile_email
        - first_name
        - last_name
      properties:
        user_profile_email:
          type: string
        first_name:
          type: string
        last_name:
          type: string
    UserCompanyAssociation:
      type: object
      required:
        - member_of
        - invited_to
      properties:
        member_of:
          type: array
          items:
            $ref: '#/components/schemas/UUID'
        invited_to:
          type: array
          items:
            $ref: '#/components/schemas/UUID'
        owner_of:
          $ref: '#/components/schemas/UUID'
    UserSettings:
      type: object
      required:
        - night_mode_active
      properties:
        night_mode_active:
          type: boolean
    UserSubscription:
      type: object
      required:
        - subscribed
      properties:
        subscribed:
          type: boolean
        subscribedUntil:
          type: string
          format: date-time
    UserRegistrationRequest:
      type: object
      required:
        - user_profile_email
        - first_name
        - last_name
      properties:
        user_profile_email:
          type: string
        first_name:
          type: string
        last_name:
          type: string
    DeleteUserByUserProfileEmailRequest:
      type: object
      required:
        - user_profile_email
      properties:
        user_profile_email:
          type: string
    ExtendUserSubscriptionRequest:
      type: object
      required:
        - extend_by_in_days
      properties:
        extend_by_in_days:
          type: integer
    AcceptCompanyInvitationRequest:
      type: object
      required:
        - company_id
      properties:
        company_id:
          $ref: '#/components/schemas/UUID'
    UpdateUserProfileRequest:
      type: object
      required:
        - user_profile_email
        - first_name
        - last_name
      properties:
        user_profile_email:
          type: string
        first_name:
          type: string
        last_name:
          type: string
    UpdateUserSettingsRequest:
      type: object
      required:
        - night_mode_active
      properties:
        night_mode_active:
          type: boolean
    UpdateCompanyDataRequest:
      type: object
      properties:
        details:
          $ref: '#/components/schemas/UpdateCompanyDetailsRequest'
        settings:
          $ref: '#/components/schemas/UpdateCompanyLinksRequest'
    UpdateCompanyDetailsRequest:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        tags:
          type: array
          uniqueItems: true
          items:
            type: string
        location:
          type: string
    UpdateCompanyLinksRequest:
      type: object
      properties:
        homepage:
          type: string
        social_media:
          type: array
          uniqueItems: true
          items:
            type: string
    PaginatedPublicCompanyProfileResponse:
      type: object
      properties:
        pagination:
          $ref: '#/components/schemas/Pagination'
        content:
          type: array
          items:
            $ref: '#/components/schemas/PublicCompanyProfile'
    PublicCompanyProfile:
      type: object
      required:
        - id
        - details
        - links
      properties:
        id:
          $ref: '#/components/schemas/UUID'
        details:
          $ref: '#/components/schemas/CompanyDetails'
        links:
          $ref: '#/components/schemas/CompanyLinks'
    Company:
      type: object
      required:
        - id
        - owner
        - members
        - details
        - links
        - partner_program
      properties:
        id:
          $ref: '#/components/schemas/UUID'
        owner:
          $ref: '#/components/schemas/UUID'
        members:
          type: array
          uniqueItems: true
          items:
            $ref: '#/components/schemas/UUID'
        details:
          $ref: '#/components/schemas/CompanyDetails'
        links:
          $ref: '#/components/schemas/CompanyLinks'
        partner_program:
          $ref: '#/components/schemas/CompanyPartnerProgram'
    CompanyDetails:
      type: object
      required:
        - name
        - description
        - tags
      properties:
        name:
          type: string
        description:
          type: string
        tags:
          type: array
          uniqueItems: true
          items:
            type: string
        location:
          type: string
    CompanyLinks:
      type: object
      properties:
        website_url:
          type: string
        social_media:
          type: array
          uniqueItems: true
          items:
            type: string
    CompanyPartnerProgram:
      type: object
      required:
        - partnered
      properties:
        partnered:
          type: boolean
        partner_until:
          type: string
          format: date-time
    CompanyRegistrationRequest:
      type: object
      required:
        - owner_id
        - details
      properties:
        owner_id:
          $ref: '#/components/schemas/UUID'
        details:
          $ref: '#/components/schemas/CompanyDetails'
        links:
          $ref: '#/components/schemas/CompanyLinks'
    CompanyInviteUserRequest:
      type: object
      properties:
        user_profile_email:
          type: string
    Pagination:
      type: object
      required:
        - total_pages
        - current_page
        - total_item_count
        - item_count
      properties:
        total_pages:
          type: integer
        current_page:
          type: integer
        total_item_count:
          type: integer
          format: int64
        item_count:
          type: integer
    UUID:
      type: string
      format: UUID
    ThrowableProblem:
      type: object
      description: Response object, which is returned if an error occurred while processing the request.
      required:
        - title
        - status
      properties:
        title:
          type: string
        status:
          type: string
        detail:
          type: string
        code:
          type: number
