spring:
  activeProfile: docker

localConfig:
  # This config is based on your machine.
  #
  # For Docker Desktop + Windows the path starts with /run/desktop/mnt/host
  # and then the drive + location of the git repository + "/volumes"
  # Example: /run/desktop/mnt/host/d/git-repos/cnd-joboffers/volumes
  #
  # For Docker Desktop + Mac you can use the absolute path of the volumes folder.
  # Just make sure the parent folder is in the configured shared folders of Docker Desktop (/Users/* is shared by default; See Docker Desktop settings)
  mountBasePath: " /run/desktop/mnt/host/d/Dev/carl-repo/cnd-joboffers/volumes"

microservices:
  authService:
    name: auth-service
    serviceName: auth-svc
    port: "8080"
    image: caschuen/cnd-joboffers-auth-service
    imageTag: latest
    url: "http://{{ .Values.microservices.authService.serviceName }}:{{ .Values.microservices.authService.port }}"
    dbName: auth-service
    jwtPublicKeyBase64: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAhweBNtTB1Cp78qyBRuhvqVjcT/DwZYKcaakP3aR83OlQ3rwKhvlvH10afx1w0aSOaO/efUYvwAl+R6/4V+RJPLDXcrAwe7dTQ9Ba8dmFx/A9ge9NtPqyvmDbx9eKEIEjOHNYmSBauDnHCxQIkL58BoSipfKEZngXMrEvBL9MGNZ00gl3aLkqbbf/6yWRtpN3BFsUgTTsau/dcJqcSr92aRzJG77683PEX4UqJi2XeEci589+OeS9Xk3hf4UPMHiQjJOogDfaQg9z0ErIIJbumi0as9Pw0/m8BIHykL9LrJc+37Zs74YJbgbVWhrJ4cBhFdmITserae91YwJ9G3LrBwIDAQAB
    jwtKeyId: 4dbacae9-3b24-46c0-8ecb-332b9bdd25ec
    jwtValidityInSeconds: "86400"
    jwtRsaSigningAlgorithm: RS256
  userService:
    name: user-service
    serviceName: user-svc
    port: "8080"
    image: caschuen/cnd-joboffers-user-service
    imageTag: latest
    url: "http://{{ .Values.microservices.userService.serviceName }}:{{ .Values.microservices.userService.port }}"
    dbName: user-service
  careerService:
    name: career-service
    serviceName: career-svc
    port: "8080"
    image: caschuen/cnd-joboffers-career-service
    imageTag: latest
    url: "http://{{ .Values.microservices.careerService.serviceName }}:{{ .Values.microservices.careerService.port }}"
    dbName: career-service
    oAuth2ClientID: career-service
    oAuth2ClientSecretEncrypted: $2a$10$1KgYAGEqhADDPvEzxZ7Q0OtPfPrKo8ZDTJAd1SG342YVdT9XNZQN6
  notificationService:
    name: notification-service
    serviceName: notification-svc
    port: "8080"
    image: caschuen/cnd-joboffers-notification-service
    imageTag: latest
  frontend:
    name: frontend
    serviceName: frontend
    port: "80"
    image: caschuen/cnd-joboffers-frontend
    imageTag: latest
    url: "http://{{ .Values.microservices.frontend.serviceName }}:{{ .Values.microservices.frontend.port }}"
    oidc:
      discoveryEndpoint: https://accounts.google.com
      clientID: 1059672486285-gea53vidspg5m9ff1d6mg5q5vjigva1t.apps.googleusercontent.com
      clientRedirectUrl: http://localhost

ingress:
  url: http://localhost
  endpoints:
    auth:
      endpoint: /auth
      serviceName: "{{ .Values.microservices.authService.serviceName }}"
      port: "{{ .Values.microservices.authService.port }}"
      externalUrl: "{{ .Values.ingress.url }}{{ .Values.ingress.endpoints.auth.endpoint }}"
    user:
      endpoint: /user
      serviceName: "{{ .Values.microservices.userService.serviceName }}"
      port: "{{ .Values.microservices.userService.port }}"
      externalUrl: "{{ .Values.ingress.url }}{{ .Values.ingress.endpoints.user.endpoint }}"
    career:
      endpoint: /career
      serviceName: "{{ .Values.microservices.careerService.serviceName }}"
      port: "{{ .Values.microservices.careerService.port }}"
      externalUrl: "{{ .Values.ingress.url }}{{ .Values.ingress.endpoints.career.endpoint }}"
    frontend:
      endpoint: ""
      serviceName: "{{ .Values.microservices.frontend.serviceName }}"
      port: "{{ .Values.microservices.frontend.port }}"

mongodb:
  name: mongodb
  serviceName: mongodb
  port: "27017"
  imageTag: "4.4.6"
  initUser: root
  initPassword: root
  startupScript: |
    db.getSiblingDB("{{ .Values.microservices.authService.dbName }}").Clients.insertOne({
      "_id": "{{ .Values.microservices.careerService.oAuth2ClientID }}",
      "encryptedPassword": "{{ .Values.microservices.careerService.oAuth2ClientSecretEncrypted }}",
      "audiences": ["user-service", "auth-service", "career-service", "notification-service"],
      "scopes": ["getUser", "getCompany"],
      "lastLogin": new Date("2023-10-11T12:58:47.275Z"),
      "lastPasswordChange": new Date("2023-10-11T12:58:47.275Z"),
      "_class": "thi.cnd.authservice.adapters.out.repository.clients.DAOs.ClientDAO"
    });

kafka:
  name: kafka
  serviceName: kafka-event
  port: "9092"
  imageTag: "7.4.3"
  bootstrapServer: "http://{{ .Values.kafka.serviceName }}:{{ .Values.kafka.port }}"
  advertisedListeners: "PLAINTEXT://{{ .Values.kafka.serviceName }}:{{ .Values.kafka.port }}"

zookeeper:
  serviceName: zookeeper
  port: "2181"
  imageTag: "7.4.3"
  connectionUrl: "{{ .Values.zookeeper.serviceName }}:{{ .Values.zookeeper.port }}"

eventstore:
  serviceName: eventstoredb
  webUIPort: "2113"
  dbPort: "1113"
  image: eventstore/eventstore
  #imageTag: 23.6.0-buster-slim
  # For ARM-based processors
  imageTag: 23.6.0-alpha-arm64v8
  connectionUrl: esdb://{{ .Values.eventstore.serviceName }}:{{ .Values.eventstore.webUIPort }}?tls=false

auth:
  internalJwtIssuerUrl: "{{ .Values.microservices.authService.url }}"
