steps:
  - name: Checkout auth-service
    uses: actions/checkout@v4
    with:
      sparse-checkout: |
        authservice
      sparse-checkout-cone-mode: false

  - name: Set up JDK 21
    uses: actions/setup-java@v3
    with:
      java-version: '21'
      distribution: 'oracle'
      architecture: x64

  - name: Validate Gradle wrapper
    uses: gradle/wrapper-validation-action@v1