name: auth-service-pipeline

on:
  push:
    branches: "*"
    paths:
      - .github/workflows/auth-service.yml
      - authservice/**

defaults:
  run:
    working-directory: ./authservice

jobs:
  jar-build-x-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout auth-service
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            authservice
          sparse-checkout-cone-mode: false

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'oracle'
          architecture: x64

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build bootJar
        run: ./gradlew bootJar --info

      - name: Execute unit tests
        run: ./gradlew test --info

      - name: Archive Jar
        uses: actions/upload-artifact@v3
        with:
          name: auth-service-jar
          path: |
            authservice/build

  docker-build-x-push:
    needs: jar-build-x-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Dockerfile
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            authservice/Dockerfile
          sparse-checkout-cone-mode: false

      - name: Download Jar
        uses: actions/download-artifact@v3
        with:
          name: auth-service-jar
          path: ./authservice/build

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./authservice
          file: ./authservice/Dockerfile
          push: true
          tags: ${{secrets.DOCKER_USERNAME}}/cnd-joboffers-auth-service
