name: frontend-pipeline

on:
  push:
    branches: main
    paths:
      - .github/workflows/frontend.yml
      - frontend/**

defaults:
  run:
    working-directory: ./frontend

jobs:
  docker-build-x-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout frontend
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            frontend
          sparse-checkout-cone-mode: false

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: ${{secrets.DOCKER_USERNAME}}/cnd-joboffers-frontend