name: user-service-pipeline

on:
  push:
    branches: main
    paths:
      - .github/workflows/user-service.yml
      - userservice/**

defaults:
  run:
    working-directory: ./userservice

jobs:
  build-x-unit-test-x-docker-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout user-service
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            userservice
          sparse-checkout-cone-mode: false

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'oracle'
          architecture: x64

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Execute Gradle bootJar build
        run: ./gradlew bootJar

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./userservice
          file: ./userservice/Dockerfile
          push: true
          tags: ${{secrets.DOCKER_USERNAME}}/cnd-joboffers-user-service